apiVersion: v2
name: mastodon
description: Mastodon Helm Chart
type: application
version: 1.0.0
appVersion: 1.0.0
home: https://eformat.github.io/helm-charts
icon: https://avatars1.githubusercontent.com/u/68044996?s=200&v=4
kubeVersion: '>=1.11.0-0'
keywords:
- social
- mastodon
maintainers:
- name: eformat
