# Generation of Kubernetes YAML is still under development!
#
# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-3.0.1
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2021-04-25T00:47:01Z"
  labels:
    app: mastodonredis1
  name: mastodonredis1
spec:
  containers:
  - args:
    - redis-server
    command:
    - docker-entrypoint.sh
    env:
    - name: PATH
      value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    - name: TERM
      value: xterm
    - name: container
      value: podman
    - name: REDIS_VERSION
      value: 6.0.12
    - name: REDIS_DOWNLOAD_URL
      value: http://download.redis.io/releases/redis-6.0.12.tar.gz
    - name: REDIS_DOWNLOAD_SHA
      value: f16ad973d19f80f121e53794d5eb48a997e2c6a85b5be41bb3b66750cc17bf6b
    - name: HOSTNAME
      value: redis
    image: docker.io/library/redis:6.0-alpine
    name: mastodonredis1
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
      privileged: false
      readOnlyRootFilesystem: false
      seLinuxOptions: {}
    workingDir: /data
  dnsConfig: {}
  hostNetwork: true
status: {}

