---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mastodon-web.fullname" . }}
  labels:
    {{- include "mastodon-web.labels" . | nindent 4 }}
spec:
  type: {{ .Values.mastodon_web.service.type }}
  ports:
    - port: {{ .Values.mastodon_web.service.port1 }}
      targetPort: tcp-3000
      protocol: TCP
      name: mastodon-web
  selector:
    {{- include "mastodon-web.selectorLabels" . | nindent 4 }}
