---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mastodon-streaming.fullname" . }}
  labels:
    {{- include "mastodon-streaming.labels" . | nindent 4 }}
spec:
  type: {{ .Values.mastodon_web.service.type }}
  ports:
    - port: {{ .Values.mastodon_streaming.service.port1 }}
      targetPort: tcp-4000
      protocol: TCP
      name: mastodon-streaming
  selector:
    {{- include "mastodon-streaming.selectorLabels" . | nindent 4 }}
