---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mastodon.name" . }}
  labels:
    app: {{ include "mastodon.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  s3_bucket: {{ .Values.mastodon.s3_bucket | b64enc | quote }}
  s3_endpoint: {{ include "mastodon.s3_endpoint" . | b64enc | quote }}
  s3_hostname: {{ include "minio.fullname" . | b64enc | quote }}
  s3_protocol: {{ .Values.mastodon.s3_protocol | b64enc | quote }}
  s3_enabled: {{ .Values.mastodon.s3_enabled | b64enc | quote }}  
  aws_access_key_id: {{ .Values.mastodon.aws_access_key_id | b64enc | quote }}
  aws_secret_access_key: {{ .Values.mastodon.aws_secret_access_key | b64enc | quote }}
  redis_host: {{ include "redis.fullname" . | b64enc | quote }}
  es_enabled: {{ default "false" | b64enc | quote }}
  es_host: {{ default "localhost" | b64enc | quote }}
  local_domain: {{ .Values.mastodon.local_domain | b64enc | quote }}
  db_host: {{ include "postgresql.fullname" . | b64enc | quote }}
  db_pass: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}
  db_user: {{ .Values.postgresql.postgresqlUsername | b64enc | quote }}
  db_name: {{ .Values.postgresql.postgresqlDatabase | b64enc | quote }}
  bind: {{ default "0.0.0.0" | b64enc | quote }}
  smtp_password: {{ default "" | b64enc | quote }}
  smtp_from_address: {{ "notificatons@example.com" | b64enc | quote }}
  smtp_login:  {{ default "" | b64enc | quote }}
  smtp_server:  {{ default "smtp.mailgun.org" | b64enc | quote }}
  vapid_public_key: {{ .Values.mastodon.vapid_public_key | b64enc | quote }}
  secret_key_base: {{ .Values.mastodon.secret_key_base | b64enc | quote }}
  vapid_private_key: {{ .Values.mastodon.vapid_private_key | b64enc | quote }}
  otp_secret: {{ .Values.mastodon.otp_secret | b64enc | quote }}