{{- if .Values.route.enabled -}}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "mastodon-web.fullname" . }}
  labels:
    {{- include "mastodon-web.labels" . | nindent 4 }}
spec:
  port:
    targetPort: tcp-8080
  to:
    kind: Service
    name: {{ include "mastodon-web.fullname" . }}
    weight: 100
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  wildcardPolicy: None
status:
  ingress:
    - conditions:
        - status: 'True'
          type: Admitted
{{ end }}
