---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql.name" . }}
  labels:
    app: {{ include "mastodon.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  postgresqlUsername: {{ .Values.postgresql.postgresqlUsername | b64enc | quote }}
  postgresqlPassword: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}
  postgresqlDatabase: {{ .Values.postgresql.postgresqlDatabase | b64enc | quote }}
