---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "redis.fullname" . }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.redis.accessMode | default " ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ .Values.redis.volume.size | default " 1Gi" }}
