---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "redis.labels" . | nindent 4 }}
  name: {{ include "redis.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "redis.selectorLabels" . | nindent 6 }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        {{- include "redis.labels" . | nindent 8 }}
    spec:
      containers:
      - image: {{ .Values.redis.image }}
        imagePullPolicy: {{ .Values.redis.pullPolicy }}
        name: redis
        ports:
        - containerPort: 6379
          name: redis
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: data
      - args:
        - 'trap : TERM INT; sleep infinity & wait'
        command:
        - /bin/bash
        - -c
        image: {{ .Values.redis.healthimage }}
        imagePullPolicy: {{ .Values.redis.pullPolicy }}
        livenessProbe:
          exec:
            command:
            - /usr/local/bin/docker-healthcheck
          failureThreshold: 30
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
        name: healthcheck
        readinessProbe:
          exec:
            command:
            - /usr/local/bin/docker-healthcheck
          failureThreshold: 30
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      hostname: redis
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ include "redis.fullname" . }}
